//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoviesCupApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoviesCupApp.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose 8 movies to start the Cup.
        /// </summary>
        internal static string Choose8Movies {
            get {
                return ResourceManager.GetString("Choose8Movies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cup Result.
        /// </summary>
        internal static string CupResult {
            get {
                return ResourceManager.GetString("CupResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet problems. Please, try again later..
        /// </summary>
        internal static string InternetProblems {
            get {
                return ResourceManager.GetString("InternetProblems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load movies.
        /// </summary>
        internal static string LoadMovies {
            get {
                return ResourceManager.GetString("LoadMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movies to list. Tap Load Movies in the top menu..
        /// </summary>
        internal static string NoMovies {
            get {
                return ResourceManager.GetString("NoMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops....
        /// </summary>
        internal static string Oops {
            get {
                return ResourceManager.GetString("Oops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifying Phase.
        /// </summary>
        internal static string QualifyingPhase {
            get {
                return ResourceManager.GetString("QualifyingPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action will reload the list and will unmark all the items.
        /// </summary>
        internal static string RefreshConfirmation {
            get {
                return ResourceManager.GetString("RefreshConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runner-up.
        /// </summary>
        internal static string RunnerUp {
            get {
                return ResourceManager.GetString("RunnerUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected movie.
        /// </summary>
        internal static string SelectedMovie {
            get {
                return ResourceManager.GetString("SelectedMovie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected movies.
        /// </summary>
        internal static string SelectedMovies {
            get {
                return ResourceManager.GetString("SelectedMovies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Star again with different movies.
        /// </summary>
        internal static string StartAgain {
            get {
                return ResourceManager.GetString("StartAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Winner.
        /// </summary>
        internal static string Winner {
            get {
                return ResourceManager.GetString("Winner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose 8 movies to start the Cup.
        /// </summary>
        internal static string WrongSizeMoviesList {
            get {
                return ResourceManager.GetString("WrongSizeMoviesList", resourceCulture);
            }
        }
    }
}
